INSERT INTO Countries VALUES ('Nigeria',1,0,GETDATE());


INSERT INTO States VALUES (1,'Abia',1,0,GETDATE());
INSERT INTO States VALUES (1,'Adamawa',1,0,GETDATE());
INSERT INTO States VALUES (1,'Akwa-Ibom',1,0,GETDATE());
INSERT INTO States VALUES (1,'Anambra',1,0,GETDATE());
INSERT INTO States VALUES (1,'Bauchi',1,0,GETDATE());
INSERT INTO States VALUES (1,'Bayalsa',1,0,GETDATE());
INSERT INTO States VALUES (1,'Benue',1,0,GETDATE());
INSERT INTO States VALUES (1,'Borno',1,0,GETDATE());
INSERT INTO States VALUES (1,'Cross-River',1,0,GETDATE());
INSERT INTO States VALUES (1,'Delta',1,0,GETDATE());
INSERT INTO States VALUES (1,'Ebonyi',1,0,GETDATE());
INSERT INTO States VALUES (1,'Edo',1,0,GETDATE());
INSERT INTO States VALUES (1,'Ekiti',1,0,GETDATE());
INSERT INTO States VALUES (1,'Enugu',1,0,GETDATE());
INSERT INTO States VALUES (1,'Gombe',1,0,GETDATE());
INSERT INTO States VALUES (1,'Imo',1,0,GETDATE());
INSERT INTO States VALUES (1,'Jigawa',1,0,GETDATE());
INSERT INTO States VALUES (1,'Kaduna',1,0,GETDATE());
INSERT INTO States VALUES (1,'Kano',1,0,GETDATE());
INSERT INTO States VALUES (1,'Katsina',1,0,GETDATE());
INSERT INTO States VALUES (1,'Kebbi',1,0,GETDATE());
INSERT INTO States VALUES (1,'Kogi',1,0,GETDATE());
INSERT INTO States VALUES (1,'Kwara',1,0,GETDATE());
INSERT INTO States VALUES (1,'Lagos',1,0,GETDATE());
INSERT INTO States VALUES (1,'Nasarawa',1,0,GETDATE());
INSERT INTO States VALUES (1,'Niger',1,0,GETDATE());
INSERT INTO States VALUES (1,'Ogun',1,0,GETDATE());
INSERT INTO States VALUES (1,'Ondo',1,0,GETDATE());
INSERT INTO States VALUES (1,'Osun',1,0,GETDATE());
INSERT INTO States VALUES (1,'Oyo',1,0,GETDATE());
INSERT INTO States VALUES (1,'Plateau',1,0,GETDATE());
INSERT INTO States VALUES (1,'River',1,0,GETDATE());
INSERT INTO States VALUES (1,'Sokoto',1,0,GETDATE());
INSERT INTO States VALUES (1,'Taraba',1,0,GETDATE());
INSERT INTO States VALUES (1,'Yobe',1,0,GETDATE());
INSERT INTO States VALUES (1,'Zamfara',1,0,GETDATE());

INSERT INTO Hostels VALUES ('Hostel A',1,0,GETDATE());
INSERT INTO Hostels VALUES ('Hostel B',1,0,GETDATE());
INSERT INTO Hostels VALUES ('Hostel C',1,0,GETDATE());
INSERT INTO Hostels VALUES ('Hostel D',1,0,GETDATE());
INSERT INTO Hostels VALUES ('Hostel E',1,0,GETDATE());
INSERT INTO Hostels VALUES ('Hostel F',1,0,GETDATE());

INSERT INTO Rooms VALUES (1, 3, 'Room 1',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 2',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 3',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 4',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 5',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 6',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 7',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 8',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 9',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 10',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 11',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 12',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 13',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 14',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 15',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 16',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 17',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 18',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 19',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 20',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 21',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 22',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 23',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 24',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 25',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 26',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 27',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 28',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 29',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 30',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 31',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 32',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 33',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 34',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 35',1,0,GETDATE());
INSERT INTO Rooms VALUES (1, 3, 'Room 36',1,0,GETDATE());


INSERT INTO CommonDropdowns VALUES (1,'Male',1,0,GETDATE());
INSERT INTO CommonDropdowns VALUES (1,'Female',1,0,GETDATE());


INSERT INTO CommonDropdowns VALUES (2,'Staff',1,0,GETDATE());
INSERT INTO CommonDropdowns VALUES (2,'Academy',1,0,GETDATE());
INSERT INTO CommonDropdowns VALUES (2,'Senior Developer',1,0,GETDATE());


INSERT INTO AspNetRoles VALUES (NEWID(),'Admin','ADMIN',NEWID() );
INSERT INTO AspNetRoles VALUES (NEWID(),'User','USER',NEWID() );